### ISSUE TITLE
Config should be trusted by default?

### ISSUE THREAD

**Issue by fiadliel** [jdxcode/rtx-action#117]
If a `.rtx.toml` is provided with dangerous features, the file is untrusted, and installing the action fails with:
> ```
> Config file is not trusted.
> Trust it with `rtx trust`.
> ```

This can be trusted in GHA config with
```yaml
    env:
      RTX_TRUSTED_CONFIG_PATHS: ${{ vars.GITHUB_WORKSPACE }}
```
but I don't think this is obvious.

Should the config file be trusted by default?

**Comment by jdxcode** [comment]
it's probably safe to always trust all configs running inside of a CI environment. I'd accept a PR for this

**Comment by fiadliel** [comment]
After further thought, I'm less certain about this.

People may use rtx in environments where PRs may come in from unknown users. I'm not sure what the right approach should be, there's no obvious easy mechanism to, for example, trust `.rtx.toml` unless it has changed. But if these features are dangerous for arbitrary untrusted downloads, they are probably also dangerous for arbitrary untrusted PR updates.

Is it acceptable that people just depend on the access controls in their CI system, and if they can run a PR, they're trusted?

**Comment by jdxcode** [comment]
I don't see how that's a problem. If you're executing a PR from an unknown user you're already running untrusted code.
