### ISSUE TITLE
Possible issues with v1.1.2

### ISSUE THREAD

**Issue by geoah** [jdxcode/rtx-action#53]
Hey there, I seem to be having a weird issues with the 1.1.2 release, but I'm not really sure how to debug.

```
Run jdxcode/rtx-action@v1
  with:
  env:
    GITHUB_TOKEN: ***
/usr/bin/curl https://rtx.pub/rtx-latest-linux-x64 --output /home/runner/.local/share/rtx/bin/rtx
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20.3M  100 20.3M    0     0   102M      0 --:--:-- --:--:-- --:--:--  102M
/usr/bin/chmod +x /home/runner/.local/share/rtx/bin/rtx
/home/runner/.local/share/rtx/bin/rtx --version
1.27.8 linux-x64 (a4c49ec 2023-03-25)
/home/runner/.local/share/rtx/bin/rtx bin-paths
[WARN] Tools not installed: golangci-lint@1.51.2, goreleaser@1.16.1, task@3.22.0, golang@1.20.2
```
Note the last line, "[WARN] Tools not installed".
The tool file used was pretty much:

```
golangci-lint 1.51.2
goreleaser    1.16.1
task          3.22.0
golang        1.20.2
```

The run can be found here: https://github.com/nimona/go-nimona/actions/runs/4535188052/jobs/7990590802

Not sure what I'm missing, but reverting to 1.1.1 resolved the issue.
It might be a misconfiguration on my end but I'm not sure what that would be.
Any suggestions / docs on how to debug this would be appreciated

**Comment by jdxcode** [comment]
oh I made a mistake, I can fix this

**Comment by geoah** [comment]
Owh wow that was fast :D @jdxcode thank you very much for a very quick fix.
