### ISSUE TITLE
Integrate Caching

### ISSUE THREAD

**Issue by rplankenhorn** [jdxcode/rtx-action#55]
Would be great if caching of installed plugins was handled inside the action.  Maybe by passing a boolean input.  It's probably not necessary to cache the the executable since that's a quick download but the plugins would really speed up execution.

**Comment by jdxcode** [comment]
Yep, agreed on both. Some plugins don't benefit from this like node since it's using precompiled binaries, but Python and Ruby compile so they would greatly benefit

**Comment by HipsterBrown** [comment]
Here is an example of use the `actions/cache@v3` action to save / restore the rtx cache: https://github.com/HipsterBrown/adonis-realworld-example-app/blob/main/.github/workflows/ci.yml#L15-L24

It works quite well! Thanks for making rtx and this great action 👏

**Comment by jdxcode** [comment]
that's great, we should integrate this into the action though so you don't have to do it manually
